apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weaves.weave.alvistack.com
spec:
  group: weave.alvistack.com
  names:
    kind: Weave
    listKind: WeaveList
    plural: weaves
    singular: weave
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
